-- ============================================================
-- Make sure you run this with a role that has CREATE USER / ROLE
-- privileges.  Start by switching to ACCOUNTADMIN:
--   USE ROLE ACCOUNTADMIN;
-- ============================================================

-- 1. Dedicated warehouse
CREATE WAREHOUSE IF NOT EXISTS CALL_LOGGER_WH
  WITH WAREHOUSE_SIZE = 'XSMALL'
       AUTO_SUSPEND = 300
       AUTO_RESUME = TRUE;

-- 2. App database + schema
CREATE DATABASE IF NOT EXISTS CALL_LOGGER_DB;
CREATE SCHEMA IF NOT EXISTS CALL_LOGGER_DB.PAYROLL;

-- 3. Role for the app
CREATE ROLE IF NOT EXISTS CALL_LOGGER_ROLE;

-- 4. Grant usage on warehouse
GRANT USAGE ON WAREHOUSE CALL_LOGGER_WH TO ROLE CALL_LOGGER_ROLE;

-- 5. Schema-level access
GRANT USAGE ON DATABASE CALL_LOGGER_DB TO ROLE CALL_LOGGER_ROLE;
GRANT USAGE ON SCHEMA CALL_LOGGER_DB.PAYROLL TO ROLE CALL_LOGGER_ROLE;

-- 6. Table creation + full DML on current and future tables
GRANT CREATE TABLE ON SCHEMA CALL_LOGGER_DB.PAYROLL TO ROLE CALL_LOGGER_ROLE;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA CALL_LOGGER_DB.PAYROLL TO ROLE CALL_LOGGER_ROLE;
GRANT ALL PRIVILEGES ON FUTURE TABLES IN SCHEMA CALL_LOGGER_DB.PAYROLL TO ROLE CALL_LOGGER_ROLE;

-- 7. Create the app user — REPLACE the password below
CREATE USER IF NOT EXISTS call_logger_app
  PASSWORD = '<pick-a-strong-password>'
  LOGIN_NAME = 'call_logger_app'
  DEFAULT_ROLE = CALL_LOGGER_ROLE
  DEFAULT_WAREHOUSE = CALL_LOGGER_WH
  DEFAULT_NAMESPACE = 'CALL_LOGGER_DB.PAYROLL'
  MUST_CHANGE_PASSWORD = FALSE;

GRANT ROLE CALL_LOGGER_ROLE TO USER call_logger_app;
